<!-- Example row of columns -->
   <div class="row">
      <div class="col-md-8">
         <h2>Formal Events</h2>
         <p>There are many lovely formal events throughout the year. This is a brief list of some of them. Most of these are annual balls.</p>
      </div>
   </div>
   <div>
      <ol>
         <li><a href="https://fourthwardschool.org/events/the-all-hallows-eve-victorian-ball/">The All Hallows Eve Victorian Ball, Virginia City, NV</a></li>
         <li><a href="https://www.artdecopreservationball.com/">Art Deco Preservation Ball, San Francisco, CA</a></li>
         <li><a href="https://artdecola.org/avalon-ball-faq">The Avalon Ball</a> May 17, 2025, Catalina Island, CA</li>
         <li><a href="https://catalinaconservancy.org/event/ball/">The Catalina Conservancy Ball</a> April, Catalina Island, CA</li>
         <li><a href="https://www.fanime.com/events/#black-and-white-ball">Fanime Black and White Ball</a>, San Jose, CA</li>
         <li><a href="https://www.fantastiquecollection.com/fantastique-starfall-balltm-2025-ca">Fantastique Starfall Ball™ 2025</a>, San Francisco, CA</li>
         <li><a href="https://www.hssv.org/give/more-ways-to-give/the-fur-ball/">Fur Ball (Humane Society)</a>, San Jose, CA</li>
         <li><a href="http://gaskellball.com">The Gaskell™ Ball</a>, Oakland, CA</li>
         <li><a href="https://allevents.in/mobile/amp-event.php?event_id=10000857575179447">Annual Grand Victorian Ball</a>Delaware</li>
         <li><a href="https://fairbanksballroom.dance/dances/formal-ball/">Hollywood Glamour Ball in Fairbanks, AK</a></li>
         <li><a href="https://labyrinthmasquerade.com/">Labyrinth Masquerade</a> - Costume, rather than formal, Southern CA</li>
         <li><a href="https://www.priorattire.co.uk/events.html">Prior Attire Victorian Ball</a> in Bath, England.</li>
         <li><a href="https://www.sfopera.com/seasons/opera-ball/">SF Opera Ball</a>, San Francisco, CA</li>
         <li><a href="https://www.sfwaltzingsociety.org/">SF Waltzing Society</a>, SF Bay Area, CA</li>
         <li><a href="https://victoriandance.org/">Social Daunce Irregulars</a> November, in Pasadena, CA</li>
         <li><a href="https://www.facebook.com/vienneseball/">Stanford Viennese Ball</a>, SF Bay Area, CA</li>
         <li><a href="https://www.amherstvictoriandance.org/future-events.html">Victorian Ball (25th Annual)</a>, Buffalo, NY</li>
         <li><a href="https://wemakehistory.com/victorian-christmas-ball">Victorian Christmas Ball (24th Annual)</a> November, in Mesa, AZ</li>
      </ol>
   </div>
</div>
<!-- /container -->
