    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2>The Ball</h2>
          <p>The next ball will be on December 28th, 2024. </p>
		<h3 style="color:red">Tickets</h3>
			<p>The 2024 Gaskell Ball is sold out.</p>
			<p>You can put yourself on the wait list, but don't get your hopes up. Don't fall for scammers on Facebook, They don't have tickets.</p>
			<p>Wait list <a href="https://thegaskellball.eventbrite.com">EventBrite</a></p>
			<p>No tickets will be sold at the door.</p>
          <p><a class="btn btn-default" href="upcomingevents.html" role="button">More Info &raquo;</a></p>
        </div>
        <div class="col-md-4">
          <h2>Dance Classes</h2>
          <p>On the afternoon of the ball, in the same location, there is a 2½ hour beginner dance class. There is also very fast 30 minute class before the ball.</p>
          <p><a class="btn btn-default" href="classes.html" role="button">More Info &raquo;</a></p>
        </div>
        <div class="col-md-4">
          <h2>What to Wear</h2>
          <p>The standard of dress is formal, that means dress up! 
            When choosing your attire for the evening, bear in mind that one goal of the evening is to dance.</p>
          <p><a class="btn btn-default" href="costumes.html" role="button">More Info &raquo;</a></p>
       </div>
      </div>
    </div> <!-- /container -->
