    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2>The Ball</h2>
		<p style="color:red">The 2024 Gaskell Ball was a wild success, completely sold out, with over 600 people.</p>
		<p>We are hoping to have a 2025 ball in December.</p>

          <p><a class="btn btn-default" href="upcomingevents.html" role="button">More Info &raquo;</a></p>
        </div>
        <div class="col-md-4">
          <h2>Dance Classes</h2>
          <p>On the afternoon of the ball, in the same location, there is a 2½ hour beginner dance class. There is also very fast 30 minute class before the ball.</p>
          <p><a class="btn btn-default" href="classes.html" role="button">More Info &raquo;</a></p>
        </div>
        <div class="col-md-4">
          <h2>What to Wear</h2>
          <p>The standard of dress is formal, that means dress up! 
            When choosing your attire for the evening, bear in mind that one goal of the evening is to dance.</p>
          <p><a class="btn btn-default" href="costumes.html" role="button">More Info &raquo;</a></p>
       </div>
      </div>
    </div> <!-- /container -->
