    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-12 indented-text">

<h2>The Next Gaskell Ball: Tentative! Dec 27th, 2025</h2>
<!--a href="https://squareup.com/market/ye-gaskell-occasional-dance-society/admission-to-the-october-th-gaskell-ball-1" class="btn btn-info" role="button">Buy Tickets Now & Save!</a-->
<p/>

<div style="margin-left: 50px;">
<h3 style="color:red">The 2025 Gaskell Ball is still in the planning stages</h3>
<p>We are looking at another December ball</p>
</div>
<br>
<!-- <p>If you are interested in actually working to make this happen, reach out to us.</p> -->
<p>More photos and information on <a  href="http://facebook.com/gaskellball">Facebook</a>.</p>

<!-- <p>Costumes can include historical costumes, modern formal wear, fictional characters, cosplay, steampunk and more. Be elegant Be dramatic. Be outrageous! Please check our <a href="costumes.html">What to Wear</a> page for more information</p> -->

<H3>Music</H3>
<p>Live music will be provided by the <a href="http://www.brassworksband.com/">Brassworks Band.</a></p>

<H3>Location</H3>
<p>The ball will be held at the Oakland Scottish Rite Center, 1547 Lakeside Dr. Oakland, CA, USA</p>
<a href="location.html" class="btn btn-info" role="button">Map</a>

<h3>Schedule</h3>
<p><em>Note that the ball is starting and ending one hour earlier than previous balls. The ball will now end at 11pm</em></p>
<p><em>This schedule may change. Please check again, closer to the date of the ball</em></p>
<dl class="dl-horizontal">
        <dt>3:00pm</dt><dd><a href="classes.html">Afternoon Dance Class</a> (until 5:30pm)<dd>
        <dt>6:30pm</dt><dd> Doors open for the ball<dd>
        <dt>6:45pm</dt><dd><a href="classes.html#evening">Brief dance class/review</a><dd>
        <dt>7:30pm</dt><dd> Dancing begins<dd>
        <dt>11:00pm</dt>
    <dd> The ball ends<dd>
</dl>


<!--
<p><a href="https://squareup.com/market/ye-gaskell-occasional-dance-society/admission-to-the-october-th-gaskell-ball-1">$20 in advance.</a></p>
<p>$25 at the door.</p>
-->


        </div>
        
      </div>

      <hr>

      <div id="footer">
      </div>
    </div> <!-- /container -->
